#!/usr/bin/env bash
# vidux-completion.sh — emit shell completion scripts for vidux.
#
# Usage: vidux-completion.sh <bash|zsh|fish>
#
#
# Each completion source completes the same subcommand list maintained
# in bin/vidux plus the top-level long/short flags. Keep this list in
# sync with bin/vidux's print_top_help / main() case branches.
set -euo pipefail

# Canonical subcommand list. Order matches print_top_help() in bin/vidux.
VIDUX_SUBCOMMANDS="dev browse status steer coordinate benchmark init drift config signpost http-smoke doctor build release completion help"
VIDUX_FLAGS="--help -h --version -v"

print_usage() {
  cat <<EOF
vidux-completion.sh — emit a shell completion script to stdout.

usage: vidux-completion.sh <bash|zsh|fish>

Each form prints a self-contained completion script. Install via:
  echo 'source <(vidux completion bash)' >> ~/.bashrc
  echo 'source <(vidux completion zsh)'  >> ~/.zshrc
  vidux completion fish > ~/.config/fish/completions/vidux.fish
EOF
}

emit_bash() {
  cat <<EOF
# vidux bash completion — generated by 'vidux completion bash'.
# Install: echo 'source <(vidux completion bash)' >> ~/.bashrc
_vidux_complete() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local subcommands="${VIDUX_SUBCOMMANDS}"
  local flags="${VIDUX_FLAGS}"

  if [ "\$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( \$(compgen -W "\${subcommands} \${flags}" -- "\${cur}") )
    return 0
  fi

  case "\${COMP_WORDS[1]}" in
    help)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "\${subcommands}" -- "\${cur}") )
        return 0
      fi
      ;;
    completion)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "bash zsh fish --help -h" -- "\${cur}") )
        return 0
      fi
      ;;
    dev)
      COMPREPLY=( \$(compgen -W "--bg --help -h" -- "\${cur}") )
      return 0
      ;;
    browse)
      COMPREPLY=( \$(compgen -W "--no-open --foreground -f --port --host --root --open-host --comments-path --receipt-corpus-path --steering-path --claims-path --help -h" -- "\${cur}") )
      return 0
      ;;
    status)
      COMPREPLY=( \$(compgen -W "--root --focus --all --json --help -h" -- "\${cur}") )
      return 0
      ;;
    steer)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "enqueue list lease ack fail retry dismiss --help -h" -- "\${cur}") )
      else
        COMPREPLY=( \$(compgen -W "--plan --message --source --consumer --lease-seconds --id --lease-token --code --stdin-json --store --root --all --json --help -h" -- "\${cur}") )
      fi
      return 0
      ;;
    coordinate)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "claim heartbeat checkpoint release active snapshot --help -h" -- "\${cur}") )
      else
        COMPREPLY=( \$(compgen -W "--claims-file --repo --claim --owner --lane --plan-path --task-id --claim-id --ttl-hours --summary --resume --proof --status --handoff-limit --help -h" -- "\${cur}") )
      fi
      return 0
      ;;
    benchmark)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "status validate readiness release-check schedule result-check journal-recover --help -h" -- "\${cur}") )
      else
        COMPREPLY=( \$(compgen -W "--release --schedule --receipt --fixture-root --artifact-root --journal --help -h" -- "\${cur}") )
      fi
      return 0
      ;;
    config)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "path check show init --help -h" -- "\${cur}") )
      else
        COMPREPLY=( \$(compgen -W "--config --json --strict --path --source --force --help -h" -- "\${cur}") )
      fi
      return 0
      ;;
    signpost)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "emit summary trace wrap lifecycle-smoke spawned-subagent-smoke --help -h" -- "\${cur}") )
      else
        COMPREPLY=( \$(compgen -W "--feature --action --status --duration-ms --exit-code --called --emitter --meta --log --run-id --runtime --limit --json --help -h" -- "\${cur}") )
      fi
      return 0
      ;;
    http-smoke)
      COMPREPLY=( \$(compgen -W "--url --timeout --max-sample-bytes --json --help -h" -- "\${cur}") )
      return 0
      ;;
    *)
      COMPREPLY=( \$(compgen -W "--help -h" -- "\${cur}") )
      return 0
      ;;
  esac
}
complete -F _vidux_complete vidux
EOF
}

emit_zsh() {
  cat <<EOF
#compdef vidux
# vidux zsh completion — generated by 'vidux completion zsh'.
# Install: echo 'source <(vidux completion zsh)' >> ~/.zshrc
_vidux() {
  local -a subcommands
  subcommands=(
    'dev:Start the local dev browser (foreground; auto-restart)'
    'browse:Launch the plan browser at :7191'
    'status:Print plan status across operational PLAN.md files'
    'steer:Queue or lease provider-neutral next-turn intent'
    'coordinate:Claim, checkpoint, and hand off live work surfaces'
    'benchmark:Inspect the current fail-closed benchmark authority'
    'init:Bootstrap a new plan PLAN.md from template'
    'drift:Record planned-vs-actual drift in PLAN.md'
    'config:Inspect, validate, or initialize local vidux.config.json'
    'signpost:Emit or summarize local feature signposts'
    'http-smoke:Classify local HTTP monitor budget responses'
    'doctor:Diagnose local toolchain + auth'
    'build:Run docs:build + contract tests as release gate'
    'release:Plan/ledger-gated release tag + push'
    'completion:Emit a shell completion script (bash|zsh|fish)'
    'help:Show help for vidux or a subcommand'
  )

  _arguments -C \\
    '1: :->cmd' \\
    '*::arg:->args'

  case \$state in
    cmd)
      _describe -t commands 'vidux command' subcommands
      _values 'flag' \\
        '--help[Show top-level help]' \\
        '-h[Show top-level help]' \\
        '--version[Print vidux version]' \\
        '-v[Print vidux version]'
      ;;
    args)
      case \$line[1] in
        help)
          _describe -t commands 'subcommand' subcommands
          ;;
        completion)
          _values 'shell' \\
            'bash[Emit bash completion]' \\
            'zsh[Emit zsh completion]' \\
            'fish[Emit fish completion]'
          _values 'flag' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        dev)
          _values 'flag' \\
            '--bg[Background mode]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        browse)
          _values 'flag' \\
            '--no-open[Do not open a browser]' \\
            '--foreground[Run in foreground]' \\
            '-f[Run in foreground]' \\
            '--port[Bind or reuse port]' \\
            '--host[Server bind host]' \\
            '--root[Scan root for PLAN.md files]' \\
            '--open-host[Browser URL host]' \\
            '--comments-path[Comments JSONL path]' \\
            '--receipt-corpus-path[Receipt corpus JSONL path]' \\
            '--steering-path[Local steering mailbox JSONL path]' \\
            '--claims-path[Local work-claims JSONL path]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        status)
          _values 'flag' \\
            '--root[Root path to scan]' \\
            '--focus[Repo name to prioritize]' \\
            '--all[Include empty, shipped, and stale tracked rows]' \\
            '--json[Print JSON]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        steer)
          _values 'steering command' enqueue list lease ack fail retry dismiss
          _values 'flag' \\
            '--plan[Authority PLAN.md]' \\
            '--message[Intent text]' \\
            '--source[Non-secret source label]' \\
            '--consumer[Non-secret consumer label]' \\
            '--lease-seconds[Lease lifetime]' \\
            '--id[Steering item UUID]' \\
            '--lease-token[Opaque lease token; prefer --stdin-json]' \\
            '--code[Safe failure code]' \\
            '--stdin-json[Read missing request fields from stdin]' \\
            '--store[Local steering JSONL path]' \\
            '--root[Allowed development root]' \\
            '--all[Include bodyless tombstones]' \\
            '--json[Print JSON]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        coordinate)
          _values 'coordination command' claim heartbeat checkpoint release active snapshot
          _values 'flag' \\
            '--claims-file[Work-claims JSONL path]' \\
            '--repo[Repository label]' \\
            '--claim[Exact work surface]' \\
            '--owner[Stable non-secret owner id]' \\
            '--lane[Work lane label]' \\
            '--plan-path[Authority PLAN.md]' \\
            '--task-id[Exact plan row id]' \\
            '--claim-id[Lease id]' \\
            '--ttl-hours[Lease duration]' \\
            '--summary[Checkpoint summary]' \\
            '--resume[Exact resume pointer]' \\
            '--proof[Mechanical proof receipt]' \\
            '--status[Release status]' \\
            '--handoff-limit[Maximum resumable handoffs]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        benchmark)
          _values 'benchmark command' status validate readiness release-check schedule result-check journal-recover
          _values 'flag' \\
            '--release[Authenticated evaluator release JSON]' \\
            '--schedule[Deterministic v4 schedule JSON]' \\
            '--receipt[Authenticated evaluator result receipt JSON]' \\
            '--fixture-root[Released public fixture root]' \\
            '--artifact-root[Content-addressed artifact root]' \\
            '--journal[Hash-chained journal path]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        config)
          _values 'config command' path check show init
          _values 'flag' \\
            '--config[Explicit config path]' \\
            '--json[Print JSON]' \\
            '--strict[Require live config]' \\
            '--path[Destination path]' \\
            '--source[Source config]' \\
            '--force[Overwrite destination]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        signpost)
          _values 'signpost command' emit summary trace wrap lifecycle-smoke spawned-subagent-smoke
          _values 'flag' \\
            '--feature[Feature name]' \\
            '--action[Action name]' \\
            '--status[Event status]' \\
            '--log[Log path]' \\
            '--run-id[Filter run id]' \\
            '--runtime[Runtime attribution]' \\
            '--limit[Limit trace rows]' \\
            '--json[Print JSON]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        http-smoke)
          _values 'flag' \\
            '--url[URL to smoke]' \\
            '--timeout[Total budget per URL in seconds]' \\
            '--max-sample-bytes[Maximum response sample bytes]' \\
            '--json[Print JSON]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        *)
          _values 'flag' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
      esac
      ;;
  esac
}

compdef _vidux vidux
EOF
}

emit_fish() {
  cat <<'EOF'
# vidux fish completion — generated by 'vidux completion fish'.
# Install: vidux completion fish > ~/.config/fish/completions/vidux.fish
function __vidux_no_subcommand
  set -l cmd (commandline -opc)
  if test (count $cmd) -eq 1
    return 0
  end
  return 1
end

complete -c vidux -f
complete -c vidux -n '__vidux_no_subcommand' -a dev        -d 'Start the local dev browser (foreground; auto-restart)'
complete -c vidux -n '__vidux_no_subcommand' -a browse     -d 'Launch the plan browser at :7191'
complete -c vidux -n '__vidux_no_subcommand' -a status     -d 'Print plan status across operational PLAN.md files'
complete -c vidux -n '__vidux_no_subcommand' -a steer      -d 'Queue or lease provider-neutral next-turn intent'
complete -c vidux -n '__vidux_no_subcommand' -a coordinate -d 'Claim, checkpoint, and hand off live work surfaces'
complete -c vidux -n '__vidux_no_subcommand' -a benchmark  -d 'Inspect the current fail-closed benchmark authority'
complete -c vidux -n '__vidux_no_subcommand' -a init       -d 'Bootstrap a new plan PLAN.md from template'
complete -c vidux -n '__vidux_no_subcommand' -a drift      -d 'Record planned-vs-actual drift in PLAN.md'
complete -c vidux -n '__vidux_no_subcommand' -a config     -d 'Inspect, validate, or initialize local vidux.config.json'
complete -c vidux -n '__vidux_no_subcommand' -a signpost   -d 'Emit or summarize local feature signposts'
complete -c vidux -n '__vidux_no_subcommand' -a http-smoke -d 'Classify local HTTP monitor budget responses'
complete -c vidux -n '__vidux_no_subcommand' -a doctor     -d 'Diagnose local toolchain + auth'
complete -c vidux -n '__vidux_no_subcommand' -a build      -d 'Run docs:build + contract tests as release gate'
complete -c vidux -n '__vidux_no_subcommand' -a release    -d 'Plan/ledger-gated release tag + push'
complete -c vidux -n '__vidux_no_subcommand' -a completion -d 'Emit a shell completion script'
complete -c vidux -n '__vidux_no_subcommand' -a help       -d 'Show help for vidux or a subcommand'

complete -c vidux -n '__vidux_no_subcommand' -l help    -s h -d 'Show top-level help'
complete -c vidux -n '__vidux_no_subcommand' -l version -s v -d 'Print vidux version'

complete -c vidux -n '__fish_seen_subcommand_from dev' -l bg                       -d 'Background mode'
complete -c vidux -n '__fish_seen_subcommand_from dev' -l help    -s h             -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from browse' -l no-open               -d 'Do not open a browser'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l foreground -s f       -d 'Run in foreground'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l port                  -d 'Bind or reuse port'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l host                  -d 'Server bind host'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l root                  -d 'Scan root for PLAN.md files'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l open-host             -d 'Browser URL host'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l comments-path         -d 'Comments JSONL path'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l receipt-corpus-path   -d 'Receipt corpus JSONL path'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l steering-path         -d 'Local steering mailbox JSONL path'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l claims-path           -d 'Local work-claims JSONL path'
complete -c vidux -n '__fish_seen_subcommand_from browse' -l help  -s h            -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from status' -l root                  -d 'Root path to scan'
complete -c vidux -n '__fish_seen_subcommand_from status' -l focus                 -d 'Repo name to prioritize'
complete -c vidux -n '__fish_seen_subcommand_from status' -l all                   -d 'Include empty, shipped, and stale tracked rows'
complete -c vidux -n '__fish_seen_subcommand_from status' -l json                  -d 'Print JSON'
complete -c vidux -n '__fish_seen_subcommand_from status' -l help  -s h            -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from steer' -a 'enqueue list lease ack fail retry dismiss' -d 'Steering command'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l plan                  -d 'Authority PLAN.md'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l message               -d 'Intent text'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l source                -d 'Non-secret source label'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l consumer              -d 'Non-secret consumer label'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l lease-seconds         -d 'Lease lifetime'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l id                    -d 'Steering item UUID'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l lease-token           -d 'Opaque lease token; prefer --stdin-json'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l code                  -d 'Safe failure code'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l stdin-json            -d 'Read missing request fields from stdin'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l store                 -d 'Local steering JSONL path'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l root                  -d 'Allowed development root'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l all                   -d 'Include bodyless tombstones'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l json                  -d 'Print JSON'
complete -c vidux -n '__fish_seen_subcommand_from steer' -l help -s h             -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from coordinate' -a 'claim heartbeat checkpoint release active snapshot' -d 'Coordination command'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l claims-file       -d 'Work-claims JSONL path'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l repo              -d 'Repository label'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l claim             -d 'Exact work surface'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l owner             -d 'Stable non-secret owner id'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l lane              -d 'Work lane label'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l plan-path         -d 'Authority PLAN.md'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l task-id           -d 'Exact plan row id'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l claim-id          -d 'Lease id'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l ttl-hours         -d 'Lease duration'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l summary           -d 'Checkpoint summary'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l resume            -d 'Exact resume pointer'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l proof             -d 'Mechanical proof receipt'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l status            -d 'Release status'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l handoff-limit     -d 'Maximum resumable handoffs'
complete -c vidux -n '__fish_seen_subcommand_from coordinate' -l help -s h         -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from benchmark' -a 'status validate readiness release-check schedule result-check journal-recover' -d 'Benchmark command'
complete -c vidux -n '__fish_seen_subcommand_from benchmark' -l release            -d 'Authenticated evaluator release JSON'
complete -c vidux -n '__fish_seen_subcommand_from benchmark' -l schedule           -d 'Deterministic v4 schedule JSON'
complete -c vidux -n '__fish_seen_subcommand_from benchmark' -l receipt            -d 'Authenticated evaluator result receipt JSON'
complete -c vidux -n '__fish_seen_subcommand_from benchmark' -l fixture-root       -d 'Released public fixture root'
complete -c vidux -n '__fish_seen_subcommand_from benchmark' -l artifact-root      -d 'Content-addressed artifact root'
complete -c vidux -n '__fish_seen_subcommand_from benchmark' -l journal            -d 'Hash-chained journal path'
complete -c vidux -n '__fish_seen_subcommand_from benchmark' -l help -s h           -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'   -d 'Target shell'
complete -c vidux -n '__fish_seen_subcommand_from completion' -l help -s h         -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from config' -a 'path check show init'               -d 'Config command'
complete -c vidux -n '__fish_seen_subcommand_from config' -l config               -d 'Explicit config path'
complete -c vidux -n '__fish_seen_subcommand_from config' -l json                 -d 'Print JSON'
complete -c vidux -n '__fish_seen_subcommand_from config' -l strict               -d 'Require live config'
complete -c vidux -n '__fish_seen_subcommand_from config' -l path                 -d 'Destination path'
complete -c vidux -n '__fish_seen_subcommand_from config' -l source               -d 'Source config'
complete -c vidux -n '__fish_seen_subcommand_from config' -l force                -d 'Overwrite destination'
complete -c vidux -n '__fish_seen_subcommand_from config' -l help -s h             -d 'Show help'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -a 'emit summary trace wrap lifecycle-smoke spawned-subagent-smoke' -d 'Signpost command'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l feature             -d 'Feature name'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l action              -d 'Action name'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l status              -d 'Event status'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l duration-ms         -d 'Duration in milliseconds'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l exit-code           -d 'Exit code'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l called              -d 'Wrapped command name'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l emitter             -d 'Emitter runtime'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l meta                -d 'Metadata key=value'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l log                 -d 'Log path'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l run-id              -d 'Filter run id'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l runtime             -d 'Runtime attribution'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l limit               -d 'Limit trace rows'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l json                -d 'Print JSON'
complete -c vidux -n '__fish_seen_subcommand_from signpost' -l help -s h            -d 'Show help'
complete -c vidux -n '__fish_seen_subcommand_from http-smoke' -l url              -d 'URL to smoke'
complete -c vidux -n '__fish_seen_subcommand_from http-smoke' -l timeout          -d 'Total budget per URL in seconds'
complete -c vidux -n '__fish_seen_subcommand_from http-smoke' -l max-sample-bytes -d 'Maximum response sample bytes'
complete -c vidux -n '__fish_seen_subcommand_from http-smoke' -l json             -d 'Print JSON'
complete -c vidux -n '__fish_seen_subcommand_from help' -a 'dev browse status steer coordinate benchmark init drift config signpost http-smoke doctor build release completion help'
EOF
}

main() {
  if [ $# -lt 1 ]; then
    print_usage >&2
    exit 2
  fi

  case "$1" in
    bash)
      emit_bash
      ;;
    zsh)
      emit_zsh
      ;;
    fish)
      emit_fish
      ;;
    --help|-h|help)
      print_usage
      ;;
    *)
      echo "vidux-completion.sh: unknown shell: $1" >&2
      echo "supported: bash, zsh, fish" >&2
      print_usage >&2
      exit 2
      ;;
  esac
}

main "$@"
