#!/usr/bin/env bash
# vidux-completion.sh — emit shell completion scripts for vidux.
#
# Usage: vidux-completion.sh <bash|zsh|fish>
#
#
# Each completion source completes the same subcommand list maintained
# in bin/vidux plus the top-level long/short flags. Keep this list in
# sync with bin/vidux's print_top_help / main() case branches.
set -euo pipefail

# Canonical subcommand list. Order matches print_top_help() in bin/vidux.
VIDUX_SUBCOMMANDS="dev browse status init drift signpost doctor build release completion help"
VIDUX_FLAGS="--help -h --version -v"

print_usage() {
  cat <<EOF
vidux-completion.sh — emit a shell completion script to stdout.

usage: vidux-completion.sh <bash|zsh|fish>

Each form prints a self-contained completion script. Install via:
  echo 'source <(vidux completion bash)' >> ~/.bashrc
  echo 'source <(vidux completion zsh)'  >> ~/.zshrc
  vidux completion fish > ~/.config/fish/completions/vidux.fish
EOF
}

emit_bash() {
  cat <<EOF
# vidux bash completion — generated by 'vidux completion bash'.
# Install: echo 'source <(vidux completion bash)' >> ~/.bashrc
_vidux_complete() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local subcommands="${VIDUX_SUBCOMMANDS}"
  local flags="${VIDUX_FLAGS}"

  if [ "\$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( \$(compgen -W "\${subcommands} \${flags}" -- "\${cur}") )
    return 0
  fi

  case "\${COMP_WORDS[1]}" in
    help|completion)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "\${subcommands}" -- "\${cur}") )
        return 0
      fi
      ;;
    dev)
      COMPREPLY=( \$(compgen -W "--bg --help -h" -- "\${cur}") )
      return 0
      ;;
    *)
      COMPREPLY=( \$(compgen -W "--help -h" -- "\${cur}") )
      return 0
      ;;
  esac
}
complete -F _vidux_complete vidux
EOF
}

emit_zsh() {
  cat <<EOF
#compdef vidux
# vidux zsh completion — generated by 'vidux completion zsh'.
# Install: echo 'source <(vidux completion zsh)' >> ~/.zshrc
_vidux() {
  local -a subcommands
  subcommands=(
    'dev:Start the local dev browser (foreground; auto-restart)'
    'browse:Launch the plan browser at :7191'
    'status:Print active-plan status across projects/*/PLAN.md'
    'init:Bootstrap a new plan PLAN.md from template'
    'drift:Record planned-vs-actual drift in PLAN.md'
    'signpost:Emit or summarize local feature signposts'
    'doctor:Diagnose local toolchain + auth'
    'build:Run docs:build + contract tests as release gate'
    'release:Bump VERSION, tag, push'
    'completion:Emit a shell completion script (bash|zsh|fish)'
    'help:Show help for vidux or a subcommand'
  )

  _arguments -C \\
    '1: :->cmd' \\
    '*::arg:->args'

  case \$state in
    cmd)
      _describe -t commands 'vidux command' subcommands
      _values 'flag' \\
        '--help[Show top-level help]' \\
        '-h[Show top-level help]' \\
        '--version[Print vidux version]' \\
        '-v[Print vidux version]'
      ;;
    args)
      case \$line[1] in
        help|completion)
          _describe -t commands 'subcommand' subcommands
          ;;
        dev)
          _values 'flag' \\
            '--bg[Background mode]' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
        *)
          _values 'flag' \\
            '--help[Show help]' \\
            '-h[Show help]'
          ;;
      esac
      ;;
  esac
}

compdef _vidux vidux
EOF
}

emit_fish() {
  cat <<'EOF'
# vidux fish completion — generated by 'vidux completion fish'.
# Install: vidux completion fish > ~/.config/fish/completions/vidux.fish
function __vidux_no_subcommand
  set -l cmd (commandline -opc)
  if test (count $cmd) -eq 1
    return 0
  end
  return 1
end

complete -c vidux -f
complete -c vidux -n '__vidux_no_subcommand' -a dev        -d 'Start the local dev browser (foreground; auto-restart)'
complete -c vidux -n '__vidux_no_subcommand' -a browse     -d 'Launch the plan browser at :7191'
complete -c vidux -n '__vidux_no_subcommand' -a status     -d 'Print active-plan status across projects/*/PLAN.md'
complete -c vidux -n '__vidux_no_subcommand' -a init       -d 'Bootstrap a new plan PLAN.md from template'
complete -c vidux -n '__vidux_no_subcommand' -a drift      -d 'Record planned-vs-actual drift in PLAN.md'
complete -c vidux -n '__vidux_no_subcommand' -a signpost   -d 'Emit or summarize local feature signposts'
complete -c vidux -n '__vidux_no_subcommand' -a doctor     -d 'Diagnose local toolchain + auth'
complete -c vidux -n '__vidux_no_subcommand' -a build      -d 'Run docs:build + contract tests as release gate'
complete -c vidux -n '__vidux_no_subcommand' -a release    -d 'Bump VERSION, tag, push'
complete -c vidux -n '__vidux_no_subcommand' -a completion -d 'Emit a shell completion script'
complete -c vidux -n '__vidux_no_subcommand' -a help       -d 'Show help for vidux or a subcommand'

complete -c vidux -n '__vidux_no_subcommand' -l help    -s h -d 'Show top-level help'
complete -c vidux -n '__vidux_no_subcommand' -l version -s v -d 'Print vidux version'

complete -c vidux -n '__fish_seen_subcommand_from dev' -l bg                       -d 'Background mode'
complete -c vidux -n '__fish_seen_subcommand_from dev' -l help    -s h             -d 'Show help'

complete -c vidux -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'   -d 'Target shell'

complete -c vidux -n '__fish_seen_subcommand_from help' -a 'dev browse status init drift signpost doctor build release completion'
EOF
}

main() {
  if [ $# -lt 1 ]; then
    print_usage >&2
    exit 2
  fi

  case "$1" in
    bash)
      emit_bash
      ;;
    zsh)
      emit_zsh
      ;;
    fish)
      emit_fish
      ;;
    --help|-h|help)
      print_usage
      ;;
    *)
      echo "vidux-completion.sh: unknown shell: $1" >&2
      echo "supported: bash, zsh, fish" >&2
      print_usage >&2
      exit 2
      ;;
  esac
}

main "$@"
